Resources:
  MinhaInstanciaEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-07d9b9ddc6cd8dd30
      InstanceType: t2.micro
      KeyName: chave-aws-ada
      Tags:
        - Key: Name
          Value: MinhaInstanciaAtualizada
