Resources:
  MinhaInstanciaEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0440d3b780d96b29d
      InstanceType: t2.micro
      KeyName: chave-aws-ada
      Tags:
        - Key: Name
          Value: MinhaPrimeiraInstancia
