Parameters:
  IdDaImagem:
    Type: String
    Default: ami-0164b1692fac0729e
  NomeDaChaveSSH:
    Type: String
    Default: chave-aws-ada
  TipoDaInstancia:
    Type: String
    Default: t2.micro
  IdsDosGruposDeSeguranca:
    Type: String
    Default: sg-099f36a4602417f27
Resources:
  MinhaInstanciaEC2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref IdDaImagem
      InstanceType: !Ref TipoDaInstancia
      KeyName: !Ref NomeDaChaveSSH
      SecurityGroupIds:
        - !Ref IdsDosGruposDeSeguranca
      Tags:
        - Key: Name
          Value: MinhaInstanciaPersonalizada
